# Generated by Django 3.2.7 on 2021-12-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='compressedImage',
            new_name='image',
        ),
    ]
