# Generated by Django 3.2.7 on 2021-12-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='unique_id',
            field=models.IntegerField(default=0),
        ),
    ]
