# Generated by Django 3.2.7 on 2021-12-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='quality',
            field=models.IntegerField(choices=[(40, 40), (60, 60), (80, 80)], default=60),
        ),
    ]
