# Generated by Django 3.2.7 on 2021-09-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageCompressor', '0002_remove_imagecompressor_compressimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecompressor',
            old_name='createdAt',
            new_name='created_At',
        ),
    ]
