# Generated by Django 3.2.7 on 2021-09-10 19:55

from django.db import migrations, models
import imageCompressor.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageCompressor', '0003_rename_createdat_imagecompressor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecompressor',
            name='compressImage',
            field=models.ImageField(blank=True, null=True, upload_to=imageCompressor.models.image_path),
        ),
    ]
