# Generated by Django 3.2.7 on 2021-09-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageCompressor', '0004_imagecompressor_compressimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecompressor',
            name='compressImage',
        ),
    ]
